apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "apicurio-registry"
images:
  - name: apicurio-registry-operator
    newName: docker.io/apicurio/apicurio-registry-operator
    newTag: 0.0.2
configMapGenerator:
  - name: apicurio-registry-operator-env-vars
    literals:
      - REGISTRY_IMAGE_MEM=docker.io/apicurio/apicurio-registry-mem:1.2.2.Final
      - REGISTRY_IMAGE_KAFKA=docker.io/apicurio/apicurio-registry-kafka:1.2.2.Final
      - REGISTRY_IMAGE_STREAMS=docker.io/apicurio/apicurio-registry-streams:1.2.2.Final
      - REGISTRY_IMAGE_JPA=docker.io/apicurio/apicurio-registry-jpa:1.2.2.Final
      - REGISTRY_IMAGE_INFINISPAN=docker.io/apicurio/apicurio-registry-infinispan:1.2.2.Final
vars:
  - name: REGISTRY_IMAGE_MEM
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: apicurio-registry-operator-env-vars
    fieldref:
        fieldpath: data.REGISTRY_IMAGE_MEM
  - name: REGISTRY_IMAGE_KAFKA
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: apicurio-registry-operator-env-vars
    fieldref:
        fieldpath: data.REGISTRY_IMAGE_KAFKA
  - name: REGISTRY_IMAGE_STREAMS
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: apicurio-registry-operator-env-vars
    fieldref:
        fieldpath: data.REGISTRY_IMAGE_STREAMS
  - name: REGISTRY_IMAGE_JPA
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: apicurio-registry-operator-env-vars
    fieldref:
        fieldpath: data.REGISTRY_IMAGE_JPA
  - name: REGISTRY_IMAGE_INFINISPAN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: apicurio-registry-operator-env-vars
    fieldref:
        fieldpath: data.REGISTRY_IMAGE_INFINISPAN
resources:
  - apicurioregistry_crd.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - operator.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
