apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurio-registry-operator
  template:
    metadata:
      labels:
        name: apicurio-registry-operator
    spec:
      serviceAccountName: apicurio-registry-operator
      containers:
        - name: apicurio-registry-operator
          image: apicurio-registry-operator
          imagePullPolicy: Always
          env:
            - name: REGISTRY_IMAGE_MEM
              value: $(REGISTRY_IMAGE_MEM)
            - name: REGISTRY_IMAGE_KAFKA
              value: $(REGISTRY_IMAGE_KAFKA)
            - name: REGISTRY_IMAGE_STREAMS
              value: $(REGISTRY_IMAGE_STREAMS)
            - name: REGISTRY_IMAGE_JPA
              value: $(REGISTRY_IMAGE_JPA)
            - name: REGISTRY_IMAGE_INFINISPAN
              value: $(REGISTRY_IMAGE_INFINISPAN)
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurio-registry-operator"
